[server]
enableCORS=false
enableXsrfProtection=false
runOnSave = true




[ui]
hideTopBar = true

[theme]
# Main body background color
backgroundColor = "#F9FAFB"  # Light gray

# Sidebar background color
secondaryBackgroundColor = "#ffffff"  # White
primaryColor="#8F67E6"
# Text color
textColor = "#374151"  # Dark gray

# Font
font = "sans serif"
